export const resumeData = {
  name: "Josh Menzies",
  title: "Platform Engineer",
  location: "Babylon, NY",
  email: "jmenzies722@gmail.com",
  phone: "(631) 332-4945",
  linkedin: "https://www.linkedin.com/in/josh-m123456",
  github: "https://github.com/joshmenzies",
  summary: "Platform Engineer building secure, automated, and observable infrastructure on AWS and Kubernetes. Skilled in Terraform, Python, and Go; improving reliability and speed for AI and cloud workloads.",
  experience: [
    {
      role: "DevOps / Platform Engineer",
      company: "Nectar Services Corp",
      location: "Jericho, NY",
      period: "February 2024 – Present",
      highlights: [
        "Engineered a serverless data-masking service on AWS Glue, Lambda, S3, Athena, and Macie to sanitize 1 TB+ of PostgreSQL data, reducing ETL time 40%.",
        "Architected a secure artifact-delivery platform (API Gateway, S3, CloudFront, Cognito) replacing SFTP; handles 500+ builds per month.",
        "Enhanced observability across 200+ EKS services using Datadog and OpenTelemetry, improving detection latency 40% and MTTR 25%.",
        "Implemented automated Datadog WAF rules for XSS/SQLi detection, lowering vulnerabilities 60% and enabling automated trace-based actions.",
        "Standardized Terraform and GitLab CI/CD pipelines across 5 AWS accounts, boosting provisioning 25% and reducing deployment errors 30%.",
        "Championed reusable IaC modules and cost-optimization practices adopted by 3 teams, saving $3K monthly and improving platform consistency.",
      ],
    },
    {
      role: "System Support Engineer",
      company: "Nectar Services Corp",
      location: "Jericho, NY",
      period: "November 2023 – February 2024",
      highlights: [
        "Automated Terraform + Python workflows across CI/CD, monitoring, compute, and data systems, boosting deployment speed 15% and reducing manual tasks 20%.",
        "Migrated on-prem workloads to AWS with 99.9% uptime and added Python-based health checks for continuous validation.",
        "Supported CI/CD pipelines + AWS configs for cross-functional teams, improving reliability and environment consistency.",
      ],
    },
  ],
  projects: [
    {
      name: "AI Data Pipeline Automation",
      company: "Nectar Services Corp",
      location: "Jericho, NY",
      period: "September 2025 – Present",
      description: "Serverless AI-compliant data pipeline for automated analytics and model experimentation.",
      highlights: [
        "Reduced ETL runtime 40% using automated schema discovery with Glue Crawlers and Athena.",
        "Implemented Macie-driven PII detection + masking across 1 TB+ PostgreSQL exports for compliance and audit readiness.",
        "Orchestrated event-driven Lambda pipelines with S3 lifecycle rules to reduce storage costs 20%.",
        "Automated dataset versioning and validation through Athena-based query enforcement.",
      ],
      tech: [
        "AWS Glue",
        "AWS Lambda",
        "Amazon Athena",
        "Amazon Macie",
        "SageMaker",
        "S3 Lifecycle",
        "Python",
      ],
    },
    {
      name: "Serverless Distribution Platform",
      company: "Nectar Services Corp",
      location: "Jericho, NY",
      period: "March 2025 – Present",
      description: "Secure artifact-distribution platform supporting private and public release workflows.",
      highlights: [
        "Delivered 500+ monthly artifacts using Lambda, API Gateway, S3, CloudFront, and Route 53.",
        "Integrated Cognito and IAM RBAC for secured access and auditing, reducing access-ticket overhead 25%.",
        "Automated provisioning with CloudFormation and Python Lambdas, reducing manual setup 60%+.",
        "Integrated metrics, logging, and release-workflow monitoring for real-time visibility.",
      ],
      tech: [
        "AWS Lambda",
        "API Gateway",
        "Amazon S3",
        "CloudFront",
        "Route 53",
        "Amazon Cognito",
        "IAM",
        "CloudFormation",
        "Python",
      ],
    },
  ],
  skills: {
    languages: ["Go", "Python", "Bash"],
    cloud_devops: [
      "AWS (EKS, Lambda, S3, RDS, Glue, Athena, Macie, IAM, KMS)",
      "Terraform",
      "GitLab CI/CD",
      "Docker",
      "Helm",
    ],
    monitoring_security: [
      "Datadog",
      "Prometheus",
      "OpenTelemetry",
      "WAF",
      "Secrets Manager",
      "Vault",
    ],
    collaboration: [
      "Jira",
      "Slack",
      "Confluence",
      "Agile Workflows",
    ],
  },
  education: [
    {
      degree: "B.S. Computer Engineering (Minor in Computer Science)",
      school: "University of Hartford",
      year: "2023",
    },
  ],
}

